# Example configuration file for spotctl
# Copy this to ~/.spot/config.yaml and update with your valuesExample configuration file for rackspace-spot CLI

# Your Rackspace Spot refresh token (required)
# Get this from the Rackspace Spot Console: API Access > Terraform > Get New Token
refresh-token: "your-refresh-token-here"

# Default region to use
region: "uk-lon-1"

# API base URL (default should work for most users)
base-url: "https://api.rackspacecloud.com/spot/v1"

# Enable debug output (optional)
debug: false

# Request timeout in seconds (optional)
timeout: 30
