# Example configuration file for spotctl
# Copy this to ~/.spot/config.yaml and update with your valuesExample configuration file for rackspace-spot CLI

# Your Rackspace Spot refresh token (required)
# Get this from the Rackspace Spot Console: API Access > Terraform > Get New Token
refresh-token: "your-refresh-token-here"

# Default namespace for operations (optional)
# If set, you won't need to specify --namespace on every command
#todo: In the future, namespace profiles should be supported to allow switching between namespaces without having to change this value
namespace: "my-default-namespace"

# API base URL (default should work for most users)
base-url: "https://spot.rackspace.com/apis"

# Enable debug output (optional)
debug: false

# Request timeout in seconds (optional)
timeout: 30
