# Example configuration file for rackspace-spot CLI
# Copy this to ~/.rackspace-spot.yaml and update with your values

# Your Rackspace Spot refresh token (required)
# Get this from the Rackspace Spot Console: API Access > Terraform > Get New Token
refresh-token: "your-refresh-token-here"

# Default region to use
region: "us-east-1"

# API base URL (default should work for most users)
base-url: "https://api.rackspacecloud.com/spot/v1"

# Enable debug output (optional)
debug: false

# Request timeout in seconds (optional)
timeout: 30
